// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        BarEchart: typeof import('./src/components/page-echarts/bar-echart.vue')['default']
        ElAside: typeof import('element-plus/es')['ElAside']
        ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
        ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
        ElCard: typeof import('element-plus/es')['ElCard']
        ElCol: typeof import('element-plus/es')['ElCol']
        ElContainer: typeof import('element-plus/es')['ElContainer']
        ElHeader: typeof import('element-plus/es')['ElHeader']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElMain: typeof import('element-plus/es')['ElMain']
        ElRow: typeof import('element-plus/es')['ElRow']
        ElTabPane: typeof import('element-plus/es')['ElTabPane']
        ElTabs: typeof import('element-plus/es')['ElTabs']
        HeatMap: typeof import('./src/components/page-echarts/heat-map.vue')['default']
        LineEchart: typeof import('./src/components/page-echarts/line-echart.vue')['default']
        MapEchart: typeof import('./src/components/page-echarts/map-echart.vue')['default']
        PieEchart: typeof import('./src/components/page-echarts/pie-echart.vue')['default']
        TagCloud: typeof import('./src/components/page-echarts/tag-cloud.vue')['default']
        WordEchart: typeof import('./src/components/page-echarts/word-echart.vue')['default']
    }
}

export {}
